### ISSUE TITLE
Nested repeated data

### ISSUE THREAD

**Issue by IvanKostyuk** [globalmentor/hadoop-bare-naked-local-fs#3]
I'm using pure java with Apache libraries:

- parquet-common-1.12.3
- parquet-hadoop-1.12.3
- hadoop-common-3.3.4.
- with all dependencies

No problem to read, but there is a problem to write.

Without win_utils it does not work at all.
Maybe, I set class wrongly:

```java
            Path path = new Path(INPUT_PATH);
            Configuration configuration = new Configuration();
            configuration.setClass("fs.file.impl", BareLocalFileSystem.class, org.apache.hadoop.fs.FileSystem.class);

            this.fileWriter = new ParquetWriter(path, configuration, new PocWriteSupport(this.schema));
```

Schema is read correctly from the file
```
message hive_schema {
  optional int96 registration_dttm;
  optional int32 id;
  optional binary first_name (STRING);
  optional binary last_name (STRING);
  optional binary email (STRING);
  optional binary gender (STRING);
  optional binary ip_address (STRING);
  optional binary cc (STRING);
  optional binary country (STRING);
  optional binary birthdate (STRING);
  optional double salary;
  optional binary title (STRING);
  optional binary comments (STRING);
  repeated group invoices {
    optional int64 invoiceID;
    optional binary issuedate (STRING);
    optional binary closuredate (STRING);
    optional group product {
      optional binary name (STRING);
      optional binary maker (STRING);
[newfile.zip](https://github.com/globalmentor/hadoop-bare-naked-local-fs/files/10971006/newfile.zip)
 
[newfile.zip](https://github.com/globalmentor/hadoop-bare-naked-local-fs/files/10971018/newfile.zip)

      optional binary year (STRING);
      optional double price;
      optional binary sku (STRING);
    }
    optional double amount;
    repeated group installments {
      optional int64 id;
      optional binary paymentdate (STRING);
      optional double amout;
    }
  }
}
```

what was written:
```json
{
  "registration_dttm": "2023-11-18T10:42:39.203730688",
  "id": 1,
  "first_name": "Amanda",
  "last_name": "Jordan",
  "email": "ajordan0@com.com",
  "gender": "Female",
  "ip_address": "1.197.201.2",
  "cc": "6759521864920116",
  "country": "Indonesia",
  "birthdate": "3/8/1971",
  "salary": 49756.53,
  "title": "Internal Auditor",
  "comments": "1E+02",
  "invoices": [
    {
      "invoiceID": 1,
      "issuedate": "2018-01-13",
      "closuredate": "2023-02-23",
      "product": {
        "name": "Toyota Mirai",
        "maker": "Toyota",
        "year": "2021",
        "price": 55665.99,
        "sku": "TM21-WHITE"
      },
      "amount": 41234.56,
      "installments": [
        {
          "id": 1,
          "paymentdate": "2018-02-13",
          "amout": 1234.56
        },
        {
          "id": 2,
          "paymentdate": "2018-03-12",
          "amout": 2222.22
        },
        {
          "id": 3,
          "paymentdate": "2018-04-11",
          "amout": 3333.33
        }
      ]
    },
    {
      "invoiceID": 2,
      "issuedate": "2014-11-15",
      "closuredate": "2023-12-26",
      "product": {
        "name": "Tesla Model S",
        "maker": "Tesla",
        "year": "2012",
        "price": 21212.99,
        "sku": "TM21-WHITE"
      },
      "amount": 41234.56,
      "installments": [
        {
          "id": 4,
          "paymentdate": "2014-12-13",
          "amout": 1212.99
        },
        {
          "id": 5,
          "paymentdate": "2015-11-15",
          "amout": 1111.11
        },
        {
          "id": 6,
          "paymentdate": "2016-12-26",
          "amout": 3333.33
        }
      ]
    }
  ]
}
```

when read with my code
```json
{
    "registration_dttm": "2023-11-18T10:42:39.203730688",
    "id": 1,
    "first_name": "Amanda",
    "last_name": "Jordan",
    "email": "ajordan0@com.com",
    "gender": "Female",
    "ip_address": "1.197.201.2",
    "cc": "6759521864920116",
    "country": "Indonesia",
    "birthdate": "3/8/1971",
    "salary": 49756.53,
    "title": "Internal Auditor",
    "comments": "1E+02",
    "invoices": [
      {
        "invoiceID": 1,
        "issuedate": "2018-01-13",
        "closuredate": "2023-02-23",
        "product": {
          "name": "Toyota Mirai",
          "maker": "Toyota",
          "year": "2021",
          "price": 55665.99,
          "sku": "TM21-WHITE"
        },
        "amount": 41234.56,
        "installments": [
          {
            "id": 1,
            "paymentdate": "2018-02-13",
            "amout": 1234.56
          }
        ]
      }
    ]
  }
```

In debug I saw that data was populated into ColuntConsumer with all stats and values.

When try to load to Google BigQuery it fails in a better way:
`Failed to create table: Error while reading data, error message: Read less values than expected: Actual: 1, Expected: 2. Row group: 0, Column: invoiceID`.

I conclude that metadata is written. When I write only one instance of repeated, the file opens correctly by everything.

I attached the file which is corrupted.

**Comment by IvanKostyuk** [comment]
[newfile.zip](https://github.com/globalmentor/hadoop-bare-naked-local-fs/files/10971023/newfile.zip)

**Comment by garretwilson** [comment]
Without having some code that reproduces this, it's hard for me to guess what the problem would be. This `FileSystem` implementation provides direct Java implementations to replace those that need to use winutils. I would expect that if there are more methods that need to be replaced/overridden, programming logic errors would occur during serialization and the writing would fail. But offhand I don't know what would cause writing to succeed yet corrupt data be produced.

If you could provide some small program that shows that in action, that would help us make progress here.

**Comment by IvanKostyuk** [comment]
Thank you, Garret.

I will try to rewrite my code/simplify it to a sharable one. But, as I told, it fails without winutils.
Do I use correct FileSystem (org.apache.hadoop.fs) or it should be (java.io or java.nio.file)?

**Comment by garretwilson** [comment]
> it fails without winutils.

I understood from your description that the actual writing of the data did not fail, but instead wrote corrupt data. Instead, the _reading_ of the data failed, because the data was corrupt. Of course the _reading_ of corrupt data will fail, because the data is corrupt—but the reading failing says little whether the Bare Naked Local FileSystem played any part in the corrupted data, because the corrupt data has already been written.

As I said earlier, I don't know whether this library plays any party in _writing_ corrupt data, because I would expect it to fail when writing the data, not to succeed but write corrupt data.

So can you be clear: is this library failing when writing data, or is it succeeding in writing data, but writing corrupted data?

**Comment by garretwilson** [comment]
Let me explain in simple terms:

* If the library fails when writing data, please provide a stack trace.
* If the library fails when reading non-corrupt data, please provide a stack trace.
* If the library fails when reading corrupt data, we expect it to fail when reading corrupt data, but that gives us little information about how the data got corrupt.

**Comment by garretwilson** [comment]
Have you confirmed that your program works if winutils is installed?

**Comment by IvanKostyuk** [comment]
I'm' sorry. I forgot to mention. I used winutils before I experienced the problem. Then, I found this project and it says that it should work without winutils.

Reading file works without winutils, but not writing. I still suspect winutils as a corrupter - because even with this library it still uses winutils.

Let me make a simple project where we can play with.

**Comment by garretwilson** [comment]
> I still suspect winutils as a corrupter …

Wait, you suspect winutils is corrupting data, or Bare Naked Local FileSystem is corrupting data?

Frankly I wouldn't expect either winutils nor Bare Naked Local FileSystem to _corrupt_ data.

> … even with this library it still uses winutils …

Now I'm even more confused. Why is it still using winutils? This library was meant to be used in place of winutils.

> Let me make a simple project where we can play with.

Great! I hope you can reproduce this in a little program where simply adding the line `configuration.setClass("fs.file.impl", BareLocalFileSystem.class, org.apache.hadoop.fs.FileSystem.class)` makes it fail. If you can do that, I'll download the program and see what I can find.

**Comment by IvanKostyuk** [comment]
[idea-project-parquet.zip](https://github.com/globalmentor/hadoop-bare-naked-local-fs/files/10972955/idea-project-parquet.zip)

**Comment by IvanKostyuk** [comment]
Original issue still persists. I've just noticed a lot of debug messages and I will try to work it out.

winutils does not exist and everything works. This is really great. I will check my initial set up why it was failing.

**Comment by IvanKostyuk** [comment]
I found the issue. It is in my code. I was a bit surprised though.
List and Array are not a Group. No need to call startGroup/endGroup when add iterable - just startField in the beginning and endField in the end.

I'm happy to run without `winutils`.

**Comment by garretwilson** [comment]
I'm glad this is working for you @IvanKostyuk ! Thanks for letting me know.

(I reopened the issue in order to give it a more appropriate resolution, but then I realized that "closed as not planned" is the correct resolution in GitHub; the more specific reason needs to be added as a label.)
